@server = http://localhost:4064


### CREATE ORDER
POST {{server}}/admin/Orders
Content-Type: application/json

{
    "deliveryTo_ID": "ae3047da-0236-4b06-9a6a-62033647c5f6",
    "notes": "NOTES",
        "items": [
            {
                "item_warehouse_ID": "0f51fc48-03fd-44c9-91bc-532f8906d186",
                "item_product_ID": "df87a252-5074-48cb-9417-997d3598d448",
                "qty": 1
            },
            {
                "item_warehouse_ID": "137ee1b8-dfa7-4c46-8aae-3c005a0b9676",
                "item_product_ID": "55cffb60-1b17-4391-a17e-adc233d60ee6",
                "qty": 2
            }
    ]
}


### UPDATE DELIVERY

POST  {{server}}/wh/updateDelivery
Content-Type: application/json


{}

### UPDATE ITEM COLLECT
GET  {{server}}/wh/collectItem(id='d89e5733-a650-4b0b-9801-3e43dbb7d1ed',userEmail='everly.pack.test@meta.com')


### DELETE ORDER
DELETE  {{server}}/admin/Orders(f12aa170-c0d3-4d6f-8ee5-b1b8f18cdcba)

###
POST {{server}}/wh/updateDelivery
Content-Type: application/json

{}



###

PATCH  {{server}}/admin/WarehouseOrders(530b16c0-8be3-4b63-a8bc-144bdb0614c5)
Content-Type: application/json

{
    "status_ID": "DELIVERY_IN_PROGRESS"
}

###
PATCH {{server}}/admin/Orders(0e266e04-5d96-41b1-bf74-62261b99caeb)
Content-Type: application/json

{
    "status_ID": "DELIVERY_IN_PROGRESS"
}

###

PATCH  {{server}}/wh/WarehouseOrders(1ef26827-9311-49c9-9673-54cf4a528fb7)
Content-Type: application/json

{
    "status_ID": "WAITING_FOR_PACKING"
}